### ISSUE TITLE
Segmentation fault when using Taglib.artwork with a mp3 file without artwork

### ISSUE THREAD

**Issue by jfcalvo** [almightycouch/taglib#2]
I'm getting a segmentation fault message every time that I try to execute `Taglib.artwork` using a mp3 file without artwork.

```elixir
$ iex -S mix
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, taglib} = Taglib.new("file_without_artwork.mp3")
{:ok, #Taglib<0.3923039850.2270953473.63644>}
iex(2)> Taglib.artwork(taglib)
[1]    39015 segmentation fault  iex -S mix
```

I'm using elixir taglib version `0.2.1`, and taglib library `1.11.1` installed with homebrew on MacOS 10.14.2.

I guess that the response in this case should be something like `{:error, "reason"}` and of course not a segmentation fault.

Thanks for the awesome work with the library.

**Comment by jfcalvo** [comment]
@redrabbit can you take a look to this one? Is something that can be fixed?

**Comment by redrabbit** [comment]
Hi @jfcalvo and thank you for reporting this issue.

I've added a fix to prevent the NIF from crashing and instead return `nil` or raise a `ArgumentError` exception in case of an unsupported file format.

Could you attach the MP3 file in order for me to investigate further?

**Comment by redrabbit** [comment]
You can give it a try with version [`0.2.2`](https://hex.pm/packages/taglib).

**Comment by jfcalvo** [comment]
> Hi @jfcalvo and thank you for reporting this issue.
> 
> I've added a fix to prevent the NIF from crashing and instead return `nil` or raise a `ArgumentError` exception in case of an unsupported file format.
> 
> Could you attach the MP3 file in order for me to investigate further?

Sure. I think that any MP3 without artwork will raise that segmentation fault but here you have one that have that problem (I have zipped the file because GitHub doesn't support upload a mp3).

[Debajo de mi cama.mp3.zip](https://github.com/almightycouch/taglib/files/2897128/Debajo.de.mi.cama.mp3.zip)

**Comment by jfcalvo** [comment]
> You can give it a try with version [`0.2.2`](https://hex.pm/packages/taglib).

Now is working returning `nil` in the case that the file doesn't has the artwork. 

Thanks.
