### ISSUE TITLE
Add album_artist as new function

### ISSUE THREAD

**Issue by jfcalvo** [almightycouch/taglib#3]
@redrabbit do you think there is any possibility into support the **album artist** tag adding a `album_artist` function?

In a lot of scenarios this tag is useful to avoid problems when one album has tracks with different artists. [Here you can find a longer explanation about this.](https://www.blisshq.com/music-library-management-blog/2010/10/12/how-to-use-album_artist/)

It would be very much appreciated if you consider this possibility.

Regards.

**Comment by redrabbit** [comment]
It might be possible to retrieve other tags using the more generic [Tag::properties()](https://taglib.org/api/classTagLib_1_1Tag.html#a4fb9d5edf5cf9549f23b46e7a2572c4e) function:

```
TITLE
ALBUM
ARTIST
ALBUMARTIST
SUBTITLE
TRACKNUMBER
DISCNUMBER
DATE
ORIGINALDATE
GENRE
COMMENT
```

I'm currently quiet busy but will try to implement this in a near future.

**Comment by jfcalvo** [comment]
That would be awesome @redrabbit. Thanks.

**Comment by redrabbit** [comment]
I pushed c592667 with the new [`Taglib.props/1`](https://hexdocs.pm/taglib/Taglib.html#props/1) API.
You can use the function like this:

```elixir
{:ok, t} = Taglib.new("path/to/my/song.mp3")
props = Taglib.props(t)

IO.puts "Album artist: #{props["ALBUMARTIST"]}"
```

I also released version [`0.2.3`](https://hex.pm/packages/taglib/0.2.3) on Hex.pm.

**Comment by jfcalvo** [comment]
Thanks @redrabbit I will take a look.

**Comment by jfcalvo** [comment]
Everything working perfectly!. 

Thank you very much @redrabbit
